# Generated by Django 5.2.8 on 2025-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(default='', max_length=100)),
                ('iot_gateway_id', models.CharField(max_length=100)),
                ('timeStamp', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
            ],
        ),
    ]
